In [0]:
import pandas as pd

In [0]:
data = pd.read_csv("lstm400.8.csv",engine ='python')

In [0]:
data.head()

1      2      3      4      5  ...    397    398    399    400  target
0  508.3  556.3  559.4  584.0  632.4  ...  582.7  578.9  565.4  569.5     1.0
1  561.4  553.1  560.2  553.5  545.9  ...  580.7  566.3  561.4  554.1     1.0
2  553.9  550.5  557.8  558.6  547.6  ...    0.0    0.0    0.0    0.0     1.0
3  479.0  530.6  538.2  597.9  663.7  ...  534.6  536.6  573.9  638.8     0.0
4  522.9  528.8  525.3  535.2  539.4  ...  659.9  630.9  583.7  533.8     0.0

[5 rows x 401 columns]

資料切割

In [0]:
from keras.layers import Dense, Dropout, LSTM, Embedding,MaxPooling1D,ConvLSTM2D,RNN
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

input_file = "lstm400.10.csv"

def load_data(test_split = 0.2):
    print ('Loading data...')
    df = pd.read_csv(input_file)
    X = df.iloc[:,:400].values
    y = df.iloc[:,-1].values
    min_max_scaler = preprocessing.MinMaxScaler()
    X = min_max_scaler.fit_transform(X)
    #X = preprocessing.scale(X)
    print(X)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_split)
    return pad_sequences(X_train), y_train, pad_sequences(X_test), y_test

In [0]:
def create_model(input_length):
    print ('Creating model...')
    model = Sequential()
    model.add(Embedding(input_dim = 188, output_dim = 50, input_length = input_length))
    model.add(LSTM(output_dim=256, activation='sigmoid', inner_activation='hard_sigmoid', return_sequences=True))
    model.add(Dropout(0.5))
    model.add(MaxPooling1D(pool_size=2, strides=None, padding='valid', data_format='channels_last'))
    model.add(LSTM(output_dim=256, activation='sigmoid', inner_activation='hard_sigmoid'))
    model.add(Dropout(0.5))
    model.add(Dense(1, activation='sigmoid'))

    print ('Compiling...')
    model.compile(loss='binary_crossentropy',
                  optimizer='adam',
                  metrics=['accuracy'])
    model.summary()
    return model


X_train, y_train, X_test, y_test = load_data()

model = create_model(len(X_train[0]))


print ('Fitting model...')
hist = model.fit(X_train, y_train, batch_size=1, nb_epoch=20, validation_split = 0.1, verbose = 1)

score, acc = model.evaluate(X_test, y_test, batch_size=1)
print('Test score:', score)
print('Test accuracy:', acc)

Loading data...
Creating model...


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:24: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(activation="sigmoid", return_sequences=True, units=256, recurrent_activation="hard_sigmoid")`
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:27: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(activation="sigmoid", units=256, recurrent_activation="hard_sigmoid")`


Compiling...
Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 200, 50)           9400      
_________________________________________________________________
lstm_3 (LSTM)                (None, 200, 256)          314368    
_________________________________________________________________
dropout_3 (Dropout)          (None, 200, 256)          0         
_________________________________________________________________
max_pooling1d_2 (MaxPooling1 (None, 50, 256)           0         
_________________________________________________________________
lstm_4 (LSTM)                (None, 256)               525312    
_________________________________________________________________
dropout_4 (Dropout)          (None, 256)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)   

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:44: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.


Train on 34 samples, validate on 4 samples
Epoch 1/20
34/34 [==============================] - 14s 404ms/step - loss: 1.0499 - acc: 0.4118 - val_loss: 0.7254 - val_acc: 0.5000
Epoch 2/20
34/34 [==============================] - 12s 359ms/step - loss: 0.7386 - acc: 0.5882 - val_loss: 0.6973 - val_acc: 0.5000
Epoch 3/20
34/34 [==============================] - 12s 360ms/step - loss: 0.7960 - acc: 0.4118 - val_loss: 0.6955 - val_acc: 0.5000
Epoch 4/20
34/34 [==============================] - 12s 361ms/step - loss: 0.8237 - acc: 0.4412 - val_loss: 0.6994 - val_acc: 0.5000
Epoch 5/20
34/34 [==============================] - 12s 360ms/step - loss: 0.8719 - acc: 0.4118 - val_loss: 0.7338 - val_acc: 0.5000
Epoch 6/20
34/34 [==============================] - 12s 360ms/step - loss: 0.6923 - acc: 0.5294 - val_loss: 0.7039 - val_acc: 0.5000
Epoch 7/20
34/34 [==============================] - 12s 357ms/step - loss: 0.8052 - acc: 0.4412 - val_loss: 0.6990 - val_acc: 0.5000
Epoch 8/20
34/34 [========

In [0]:
X_train, y_train, X_test, y_test = load_data()
import numpy as np
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
y_train = np.reshape(y_train, (y_train.shape[0], 1))
y_test = np.reshape(y_test, (y_test.shape[0], 1))
print(X_train.shape,X_test.shape)

Loading data...
[[0.73893199 0.7406532  0.55372204 ... 0.53861183 0.5264432  0.53031008]
 [0.86010954 0.7337774  0.55518885 ... 0.52688872 0.52271881 0.51596983]
 [0.84299407 0.7281908  0.55078841 ... 0.         0.         0.        ]
 ...
 [0.79735281 0.68650623 0.50220022 ... 0.58289914 0.59050279 0.57016482]
 [0.77247832 0.68908466 0.50770077 ... 0.52446967 0.5094041  0.50041903]
 [0.80876312 0.70176193 0.56710671 ... 0.49916263 0.4981378  0.49939473]]
(92, 400, 1) (23, 400, 1)


In [0]:
from __future__ import print_function

import numpy as np
from keras.callbacks import Callback
from keras.layers import Dense
from keras.layers import LSTM
from keras.models import Sequential
from numpy.random import choice


USE_SEQUENCES = False
USE_STATELESS_MODEL = False

# you can all the four possible combinations
# USE_SEQUENCES and USE_STATELESS_MODEL

max_len = 400
batch_size = 1

class ResetStatesCallback(Callback):
    def __init__(self):
        self.counter = 0

    def on_batch_begin(self, batch, logs={}):
        if self.counter % max_len == 0:
            self.model.reset_states()
        self.counter += 1

print('sequences_x_train shape:', X_train.shape)
print('sequences_y_train shape:', y_train.shape)

print('sequences_x_test shape:', X_test.shape)
print('sequences_y_test shape:', y_test.shape)

if USE_STATELESS_MODEL:
    print('Build STATELESS model...')
    model = Sequential()
    model.add(LSTM(10, input_shape=(max_len, 1), return_sequences=True))
    model.add(LSTM(10, input_shape=(max_len, 1), return_sequences=False))
    model.add(Dense(1, optimizer='rmsprop'))

    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    model.summary()
    print('Train...')
    model.fit(X_train, y_train, batch_size=batch_size, nb_epoch=15,
              validation_data=(X_test, y_test), shuffle=False, callbacks=[ResetStatesCallback()])

    score, acc = model.evaluate(X_test, y_test, batch_size=batch_size, verbose=0)
    print('___________________________________')
    print('Test score:', score)
    print('Test accuracy:', acc)
else:
    # STATEFUL MODEL
    print('Build STATEFUL model...')
    model = Sequential()
    model.add(LSTM(10,batch_input_shape=(1, 1, 1), return_sequences=False,stateful=True))
    model.add(Dense(1, activation='sigmoid'))

    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

    x = np.expand_dims(np.expand_dims(X_train.flatten(), axis=1), axis=1)
    y = np.expand_dims(np.array([[v] * max_len for v in y_train.flatten()]).flatten(), axis=1)
    model.fit(x,
              y,
              callbacks=[ResetStatesCallback()],
              batch_size=1,
              shuffle=False)

    print('Train...')
    for epoch in range(15):
        mean_tr_acc = []
        mean_tr_loss = []
        for i in range(len(X_train)):
            y_true = y_train[i]
            for j in range(max_len):
                tr_loss, tr_acc = model.train_on_batch(np.expand_dims(np.expand_dims(X_train[i][j], axis=1), axis=1),
                                                       np.array([y_true]))
                mean_tr_acc.append(tr_acc)
                mean_tr_loss.append(tr_loss)
            model.reset_states()

        print('accuracy training = {}'.format(np.mean(mean_tr_acc)))
        print('loss training = {}'.format(np.mean(mean_tr_loss)))
        print('___________________________________')

        mean_te_acc = []
        mean_te_loss = []
        for i in range(len(X_test)):
            for j in range(max_len):
                te_loss, te_acc = model.test_on_batch(np.expand_dims(np.expand_dims(X_test[i][j], axis=1), axis=1),
                                                      y_test[i])
                mean_te_acc.append(te_acc)
                mean_te_loss.append(te_loss)
            model.reset_states()

            for j in range(max_len):
                y_pred = model.predict_on_batch(np.expand_dims(np.expand_dims(X_test[i][j], axis=1), axis=1))
            model.reset_states()

        print('accuracy testing = {}'.format(np.mean(mean_te_acc)))
        print('loss testing = {}'.format(np.mean(mean_te_loss)))
        print('___________________________________')

sequences_x_train shape: (92, 400, 1)
sequences_y_train shape: (92, 1)
sequences_x_test shape: (23, 400, 1)
sequences_y_test shape: (23, 1)
Build STATEFUL model...
Epoch 1/1
   30/36800 [..............................] - ETA: 51:48 - loss: 0.6608 - acc: 0.9667  

/usr/local/lib/python3.6/dist-packages/keras/callbacks.py:95: RuntimeWarning: Method (on_train_batch_begin) is slow compared to the batch update (0.929320). Check your callbacks.
  % (hook_name, delta_t_median), RuntimeWarning)


36800/36800 [==============================] - 207s 6ms/step - loss: 0.1956 - acc: 0.9111
Train...
